version: "3.7"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - default
    ports:
      - "5000:5000"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - 16543:80
    depends_on:
      - db
volumes:
  data: